spring.application.name=ProjecWebService
spring.datasource.url=jdbc:postgresql://localhost:5432/testcase
spring.datasource.username=postgres
spring.datasource.password=Vuhao2005@

# câu hình sql
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

jwt.secret-key=haomilosinhraoninhbinhqualamotdieuthuyetvoiw
jwt.expired=900000